kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.pnpm-store

  - name: build
    image: gplane/pnpm:9.14
    commands:
      - pnpm i
      - pnpm build

  # - name: scp files
  #   image: appleboy/drone-scp
  #   settings:
  #     host:
  #       - mestest.aoxqwl.com
  #     username: axq
  #     password:
  #       from_secret: server_password
  #     port: 22
  #     command_timeout: 2m
  #     target: /www/wwwroot/mestest.aoxqwl.com
  #     source:
  #       - dist/*

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.pnpm-store
volumes:
  - name: cache
    host:
      path: /var/lib/cache
