kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master # 仅当分支是 dev 时触发

volumes:
  - name: cache
    host:
      path: /home/lighthouse/drone

steps:

  # 安装依赖
  - name: install_dependencies
    image: node:20
    commands:
      - npm install -g pnpm # 安装 pnpm
      - pnpm install --frozen-lockfile # 安装依赖，保持锁文件一致性

    volumes:
    - name: cache
      path: /tmp/cache