kind: pipeline
name: default

trigger:
  branch:
    - master # 仅当分支是 dev 时触发

# volumes:
#   - name: cache
#     host:
#       path: /home/lighthouse/cache

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /home/lighthouse/drone
  settings:
    restore: true
    mount:
      - ./node_modules
- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /home/lighthouse/drone
  settings:
    rebuild: true
    mount:
      - ./node_modules
