kind: pipeline
type: docker
name: default

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.pnpm-store

  - name: install dependencies
    image: gplane/pnpm:9.14
    commands:
      - pnpm i

  - name: build A
    image: gplane/pnpm:9.14
    commands:
      - pnpm build
    when:
      branch:
        - dev/a

  - name: build B
    image: gplane/pnpm:9.14
    commands:
      - pnpm build
    when:
      event:
      - promote
      target:
      - production

  - name: publish dev
    image: appleboy/drone-scp
    settings:
      host:
        - mstaging.aoxqwl.com
      username: lighthouse
      password: 1230456aA_
      port: 22
      command_timeout: 2m
      target: /home/lighthouse
      source:
        - ./dist/*

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.pnpm-store
trigger:
  branch:
    include:
      - dev/*

volumes:
  - name: cache
    host:
      path: /var/lib/cache
