kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.pnpm-store
  - name: build
    image: node:22.11.0-alpine
    commands:
      - npm install -g pnpm
      - which pnpm
      - ls /usr/local/bin/
      - pnpm i
      - pnpm build
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.pnpm-store
volumes:
  - name: cache
    host:
      path: /var/lib/cache
