---
kind: pipeline
type: docker
name: default

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.pnpm-store

  - name: install dependencies
    image: gplane/pnpm:9.14
    commands:
      - pnpm i

  - name: build A
    image: gplane/pnpm:9.14
    commands:
      - pnpm build
    when:
      branch:
        - dev/a

  - name: build B
    image: gplane/pnpm:9.14
    commands:
      - pnpm build
    when:
      event:
      - promote
      target:
      - production

  - name: publish dev
    image: appleboy/drone-scp
    settings:
      host:
        - 43.128.121.164
      username: lighthouse
      password: 1230456aA_
      port: 22
      command_timeout: 2m
      target: /home/lighthouse
      source:
        - ./apps/mes/dist/*

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.pnpm-store
trigger:
  branch:
    include:
      - dev/*

volumes:
  - name: cache
    host:
      path: /var/lib/cache


---
kind: pipeline
type: docker
name: release

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.pnpm-store

  - name: install dependencies a
    image: gplane/pnpm:9.14
    commands:
      - pnpm i

    when:
      event:
        - promote
      target:
        - a

  - name: install dependencies b
    image: gplane/pnpm:9.14
    commands:
      - pnpm i

    when:
      event:
        - promote
      target:
        - b
        
  - name: install dependencies c
    image: gplane/pnpm:9.14
    commands:
      - pnpm i

    when:
      event:
        - promote
      target:
        - c

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.pnpm-store
trigger:
  branch:
    include:
      - release
  event:
    - promote
  target:
    - a
    - b
    - c

volumes:
  - name: cache
    host:
      path: /var/lib/cache
